package com.svadhan.collection.constants;

public enum DocType {
    AADHAAR_FRONT,
    AADHAAR_BACK,
    HUSBAND_AADHAAR_FRONT,
    HUSBAND_AADHAAR_BACK,
    VOTER_ID_FRONT,
    VOTER_ID_BACK,
    HUSBAND_VOTER_ID_FRONT,
    HUSBAND_VOTER_ID_BACK,
    SELFIE_IMAGE,
    LOAN_AGREEMENT,
    CG_VOTER_ID_FRONT,
    CG_VOTER_ID_BACK,
    ELECTRICITY_BILL,
    WATER_BILL,
    BUILDING_TAX_RECEIPT,
    HOUSE_PHOTO,
    DLE_SELFIE_IMAGE
}
